# Generated by Django 2.2.13 on 2020-11-04 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字、アンスコ4文字〜20文字です。', regex='^[A-Za-z0-9_]{4,20}$')], verbose_name='名前')),
                ('url', models.URLField(help_text='https://tabocom.backlog.com', verbose_name='URL')),
                ('api_key', models.CharField(max_length=100, verbose_name='API_KEY')),
                ('project_id', models.CharField(max_length=10, verbose_name='プロジェクトID')),
                ('issuetype_id', models.CharField(max_length=10, verbose_name='種別ID')),
                ('priority_id', models.CharField(max_length=1, verbose_name='優先度ID')),
            ],
            options={
                'verbose_name': 'Backlog設定',
                'verbose_name_plural': 'Backlog設定一覧',
            },
        ),
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字、アンスコ4文字〜20文字です。', regex='^[A-Za-z0-9_]{4,20}$')], verbose_name='名前')),
                ('url', models.URLField(help_text='http://gitlab.gitlab:8085', verbose_name='URL')),
                ('access_token', models.CharField(max_length=50, verbose_name='アクセストークン')),
                ('project_id', models.CharField(max_length=5, verbose_name='プロジェクトID')),
                ('labels', models.CharField(max_length=50, verbose_name='ラベル')),
            ],
            options={
                'verbose_name': 'Gitlab設定',
                'verbose_name_plural': 'Gitlab設定一覧',
            },
        ),
        migrations.CreateModel(
            name='GoogleChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字、アンスコ4文字〜20文字です。', regex='^[A-Za-z0-9_]{4,20}$')], verbose_name='名前')),
                ('webhook', models.URLField(help_text='https://chat.googleapis.com/v1/spaces/XXXXX/messages?key=YYYYY&token=ZZZZZ', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'GoogleChat設定',
                'verbose_name_plural': 'GoogleChat設定一覧',
            },
        ),
    ]
