# Generated by Django 2.2.13 on 2021-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_redmine_redminelib_redminenote_redminevul'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmine',
            name='tracker_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Tracker ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='tracker_name',
            field=models.CharField(default='', help_text='Tracker Name, not a Tracker ID.', max_length=50, verbose_name='Tracker Name'),
            preserve_default=False,
        ),
    ]
