# Generated by Django 2.2.13 on 2020-12-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201214_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='project_key',
            field=models.CharField(default='', max_length=100, verbose_name='Project Key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backlog',
            name='api_key',
            field=models.CharField(max_length=100, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='issuetype_id',
            field=models.CharField(max_length=10, verbose_name='IssueType ID'),
        ),
        migrations.AlterField(
            model_name='gitlab',
            name='access_token',
            field=models.CharField(max_length=50, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='gitlab',
            name='owner_access_token',
            field=models.CharField(blank=True, help_text='For bulk process', max_length=50, null=True, verbose_name="Project Owner's Access Token"),
        ),
    ]
