# Generated by Django 2.2.13 on 2021-07-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210721_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redmine',
            name='tracker_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tracker ID'),
        ),
    ]
