# Generated by Django 2.2.13 on 2020-12-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201217_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='project_id',
        ),
    ]
