# Generated by Django 2.2.13 on 2020-12-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_backlog_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='issuetype',
            field=models.CharField(default='', max_length=100, verbose_name='IssueType'),
            preserve_default=False,
        ),
    ]
