# Generated by Django 2.2.13 on 2021-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_redmine_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmine',
            name='severity_id_critical',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Severity Critical ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_id_high',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Severity High ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_id_low',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Severity Low ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_id_medium',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Severity Medium ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_id_note',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Severity Note ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_name_critical',
            field=models.CharField(default='', help_text='Critical Name, not a Critical ID.', max_length=50, verbose_name='Severity Critical'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_name_high',
            field=models.CharField(default='', help_text='High Name, not a High ID.', max_length=50, verbose_name='Severity High'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_name_low',
            field=models.CharField(default='', help_text='Low Name, not a Low ID.', max_length=50, verbose_name='Severity Low'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_name_medium',
            field=models.CharField(default='', help_text='Medium Name, not a Medium ID.', max_length=50, verbose_name='Severity Medium'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='severity_name_note',
            field=models.CharField(default='', help_text='Note Name, not a Note ID.', max_length=50, verbose_name='Severity Note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_id_confirmed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Status Confirmed ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_id_fixed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Status Fixed ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_id_notaproblem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Status NotAProblem ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_id_remediated',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Status Remediated ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_id_reported',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Status Reported ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_id_suspicious',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Status Suspicious ID'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_name_confirmed',
            field=models.CharField(default='', help_text='Confirmed Name, not a Confirmed ID.', max_length=50, verbose_name='Status Confirmed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_name_fixed',
            field=models.CharField(default='', help_text='Fixed Name, not a Fixed ID.', max_length=50, verbose_name='Status Fixed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_name_notaproblem',
            field=models.CharField(default='', help_text='NotAProblem Name, not a NotAProblem ID.', max_length=50, verbose_name='Status NotAProblem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_name_remediated',
            field=models.CharField(default='', help_text='Remediated Name, not a Remediated ID.', max_length=50, verbose_name='Status Remediated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_name_reported',
            field=models.CharField(default='', help_text='Status Name, not a Status ID.', max_length=50, verbose_name='Status Reported'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redmine',
            name='status_name_suspicious',
            field=models.CharField(default='', help_text='Suspicious Name, not a Suspicious ID.', max_length=50, verbose_name='Status Suspicious'),
            preserve_default=False,
        ),
    ]
