# Generated by Django 2.2.13 on 2020-12-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_backlog_issuetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='issuetype',
        ),
        migrations.AddField(
            model_name='backlog',
            name='issuetype_name',
            field=models.CharField(default='', max_length=100, verbose_name='IssueType Name'),
            preserve_default=False,
        ),
    ]
