# Generated by Django 2.2.13 on 2020-12-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201217_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='priority_name',
            field=models.CharField(default='', max_length=100, verbose_name='Priority Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backlog',
            name='project_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='issuetype_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='IssueType ID'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='priority_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Priority ID'),
        ),
    ]
