# Generated by Django 2.2.13 on 2021-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210807_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmine',
            name='auto_create_priority',
            field=models.BooleanField(default=False, help_text='If the priority does not exist on the Redmine side, create it.', verbose_name='Create a priority'),
        ),
        migrations.AddField(
            model_name='redmine',
            name='auto_create_status',
            field=models.BooleanField(default=False, help_text='If the status does not exist on the Redmine side, create it.', verbose_name='Create a status'),
        ),
        migrations.AlterField(
            model_name='redmine',
            name='severity_id_cvelib',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vulnerable Library ID'),
        ),
        migrations.AlterField(
            model_name='redmine',
            name='severity_name_cvelib',
            field=models.CharField(default='重大', max_length=50, verbose_name='Vulnerable Library'),
        ),
    ]
