# Generated by Django 2.2.13 on 2020-12-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20201217_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='project_id',
        ),
    ]
