# Generated by Django 2.2.13 on 2021-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210807_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redmine',
            name='auto_create_priority',
        ),
        migrations.RemoveField(
            model_name='redmine',
            name='auto_create_status',
        ),
        migrations.AlterField(
            model_name='redmine',
            name='severity_name_cvelib',
            field=models.CharField(default='高', max_length=50, verbose_name='Vulnerable Library'),
        ),
    ]
