# Generated by Django 2.2.13 on 2020-12-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_backlog_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='project_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Project ID'),
        ),
    ]
