# Generated by Django 2.2.13 on 2021-08-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210809_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmine',
            name='text_format',
            field=models.CharField(choices=[('textile', 'Textile'), ('markdown', 'Markdown')], default='markdown', max_length=8, verbose_name='テキスト書式'),
        ),
    ]
