# Generated by Django 2.2.13 on 2020-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201217_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='status_confirmed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status_fixed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fixed'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status_notaproblem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Not a Problem'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status_remediated',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Remediated'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status_reported',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reported'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status_suspicious',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Suspicious'),
        ),
    ]
