# Generated by Django 2.2.13 on 2020-12-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201217_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogVul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrast_org_id', models.CharField(max_length=36, verbose_name='Organization ID')),
                ('contrast_app_id', models.CharField(max_length=36, verbose_name='Application ID')),
                ('contrast_vul_id', models.CharField(blank=True, max_length=19, null=True, verbose_name='Vulnerability ID')),
                ('backlog_issue_id', models.PositiveSmallIntegerField(verbose_name='Issue ID')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuls', related_query_name='vul', to='application.Backlog', verbose_name='Backlog')),
            ],
            options={
                'verbose_name': 'Backlog Vulnerability',
                'verbose_name_plural': 'Backlog Vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='BacklogLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrast_org_id', models.CharField(max_length=36, verbose_name='Organization ID')),
                ('contrast_app_id', models.CharField(max_length=36, verbose_name='Application ID')),
                ('contrast_lib_lg', models.CharField(blank=True, max_length=20, null=True, verbose_name='Library Language')),
                ('contrast_lib_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Library ID')),
                ('backlog_issue_id', models.PositiveSmallIntegerField(verbose_name='Issue ID')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libs', related_query_name='lib', to='application.Backlog', verbose_name='Backlog')),
            ],
            options={
                'verbose_name': 'Backlog Library',
                'verbose_name_plural': 'Backlog Libraries',
            },
        ),
        migrations.CreateModel(
            name='BacklogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('creator', models.CharField(max_length=200, verbose_name='Creator')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('contrast_note_id', models.CharField(max_length=36, unique=True, verbose_name='Contrast Note ID')),
                ('backlog_comment_id', models.PositiveSmallIntegerField(verbose_name='Backlog Comment ID')),
                ('vul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='application.BacklogVul', verbose_name='Backlog Vulnerability')),
            ],
            options={
                'verbose_name': 'Backlog Vulnerability Comment',
                'verbose_name_plural': 'Backlog Vulnerability Comments',
            },
        ),
    ]
