# Generated by Django 2.2.13 on 2020-08-24 00:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字4文字〜10文字です。', regex='^[A-Za-z0-9]{4,10}$')], verbose_name='名前')),
                ('url', models.URLField(help_text='https://tabocom.backlog.com', verbose_name='URL')),
                ('api_key', models.CharField(max_length=100, verbose_name='API_KEY')),
                ('project_id', models.CharField(max_length=10, verbose_name='プロジェクトID')),
                ('issuetype_id', models.CharField(max_length=10, verbose_name='種別ID')),
            ],
            options={
                'verbose_name': 'Backlog設定',
                'verbose_name_plural': 'Backlog設定一覧',
            },
        ),
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字4文字〜10文字です。', regex='^[A-Za-z0-9]{4,10}$')], verbose_name='名前')),
                ('url', models.URLField(help_text='http://gitlab.gitlab:8085', verbose_name='URL')),
                ('access_token', models.CharField(max_length=50, verbose_name='アクセストークン')),
                ('project_id', models.CharField(max_length=5, verbose_name='プロジェクトID')),
                ('labels', models.CharField(max_length=50, verbose_name='ラベル')),
            ],
            options={
                'verbose_name': 'Gitlab設定',
                'verbose_name_plural': 'Gitlab設定一覧',
            },
        ),
        migrations.CreateModel(
            name='TeamServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='この名前をTeamServerのPayloadに設定してください。', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字4文字〜10文字です。', regex='^[A-Za-z0-9]{4,10}$')], verbose_name='名前')),
                ('url', models.URLField(help_text='http://172.31.47.104:8080/Contrast', verbose_name='TeamServer URL')),
                ('authorization', models.CharField(max_length=100, unique=True, verbose_name='AUTHORIZATION')),
                ('api_key', models.CharField(max_length=50, unique=True, verbose_name='API_KEY')),
                ('backlog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamservers', related_query_name='teamserver', to='relay_django.Backlog', verbose_name='Backlog')),
                ('gitlab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamservers', related_query_name='teamserver', to='relay_django.Gitlab', verbose_name='Gitlab')),
            ],
            options={
                'verbose_name': 'TeamServer設定',
                'verbose_name_plural': 'TeamServer設定一覧',
            },
        ),
    ]
