# Generated by Django 2.2.13 on 2020-08-23 22:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(help_text='このIDをTeamServerのPayloadに設定してください。', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='設定IDは半角英数字10文字です。', regex='^[A-Za-z0-9]{8}$')], verbose_name='設定ID')),
                ('url', models.URLField(help_text='http://172.31.47.104:8080/Contrast', verbose_name='TeamServer URL')),
                ('authorization', models.CharField(max_length=100, unique=True, verbose_name='AUTHORIZATION')),
                ('api_key', models.CharField(max_length=50, unique=True, verbose_name='API_KEY')),
            ],
            options={
                'verbose_name': 'TeamServer設定',
                'verbose_name_plural': 'TeamServer設定一覧',
            },
        ),
        migrations.CreateModel(
            name='Gitlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='http://gitlab.gitlab:8085', verbose_name='Gitlab URL')),
                ('teamserver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relay_django.TeamServerConfig', verbose_name='TeamServer設定')),
            ],
            options={
                'verbose_name': 'Gitlab連携',
                'verbose_name_plural': 'Gitlab連携一覧',
            },
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='https://tabocom.backlog.com', verbose_name='Backlog URL')),
                ('teamserver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relay_django.TeamServerConfig', verbose_name='TeamServer設定')),
            ],
            options={
                'verbose_name': 'Backlog連携',
                'verbose_name_plural': 'Backlog連携一覧',
            },
        ),
    ]
