# Generated by Django 2.2.13 on 2021-07-21 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_redmine_redminelib_redminenote_redminevul'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='redmine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations', related_query_name='integration', to='application.Redmine', verbose_name='Redmine'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(help_text='Set this name to the TeamServer Generic Webhook Payload.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字、アンスコ1文字〜20文字です。', regex='^[A-Za-z0-9_]{1,20}$')], verbose_name='Name'),
        ),
    ]
