# Generated by Django 2.2.13 on 2020-12-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': 'Integration', 'verbose_name_plural': 'Integration List'},
        ),
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=models.CharField(max_length=50, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='service_key',
            field=models.CharField(max_length=20, verbose_name='Service Key'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='username',
            field=models.CharField(help_text='Login ID (mail address)', max_length=20, verbose_name='Username'),
        ),
    ]
