# Generated by Django 2.2.13 on 2020-12-17 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20201214_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(help_text='Set this name to the TeamServer Generic Webhook Payload.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='名前は半角英数字、アンスコ4文字〜10文字です。', regex='^[A-Za-z0-9_]{4,20}$')], verbose_name='Name'),
        ),
    ]
